# Generated by Django 2.1.1 on 2018-09-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assists', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BenchPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_from_the_bench', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FirstEleven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_played', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=64)),
                ('clubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Clubs')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Clubs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManOfTheMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('club', models.ManyToManyField(to='main.Clubs')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('position', models.IntegerField(choices=[(0, 'GK'), (1, 'DR'), (2, 'DC'), (3, 'DL'), (4, 'DM'), (5, 'MR'), (6, 'MC'), (7, 'ML'), (8, 'AMR'), (9, 'AMC'), (10, 'AML'), (11, 'ST')])),
                ('injury', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_cards', models.IntegerField()),
                ('match', models.ManyToManyField(to='main.Matches')),
                ('player', models.ManyToManyField(to='main.Players')),
            ],
        ),
        migrations.CreateModel(
            name='YellowCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow_cards', models.IntegerField()),
                ('match', models.ManyToManyField(to='main.Matches')),
                ('player', models.ManyToManyField(to='main.Players')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='players',
            field=models.ManyToManyField(to='main.Players'),
        ),
        migrations.AddField(
            model_name='manofthematch',
            name='match',
            field=models.ManyToManyField(to='main.Matches'),
        ),
        migrations.AddField(
            model_name='manofthematch',
            name='player',
            field=models.ManyToManyField(to='main.Players'),
        ),
        migrations.AddField(
            model_name='goals',
            name='match',
            field=models.ManyToManyField(to='main.Matches'),
        ),
        migrations.AddField(
            model_name='goals',
            name='player',
            field=models.ManyToManyField(to='main.Players'),
        ),
        migrations.AddField(
            model_name='firsteleven',
            name='match',
            field=models.ManyToManyField(to='main.Matches'),
        ),
        migrations.AddField(
            model_name='firsteleven',
            name='player',
            field=models.ManyToManyField(to='main.Players'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Players'),
        ),
        migrations.AddField(
            model_name='benchplayers',
            name='match',
            field=models.ManyToManyField(to='main.Matches'),
        ),
        migrations.AddField(
            model_name='benchplayers',
            name='player',
            field=models.ManyToManyField(to='main.Players'),
        ),
        migrations.AddField(
            model_name='assists',
            name='match',
            field=models.ManyToManyField(to='main.Matches'),
        ),
        migrations.AddField(
            model_name='assists',
            name='player',
            field=models.ManyToManyField(to='main.Players'),
        ),
    ]
