# Generated by Django 2.1.1 on 2018-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='club',
        ),
        migrations.AddField(
            model_name='matches',
            name='away_team',
            field=models.ManyToManyField(related_name='AwayTeam', to='main.Clubs'),
        ),
        migrations.AddField(
            model_name='matches',
            name='home_team',
            field=models.ManyToManyField(related_name='HomeTeam', to='main.Clubs'),
        ),
    ]
