# Generated by Django 2.1.1 on 2018-09-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180930_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={'verbose_name': 'club', 'verbose_name_plural': 'clubs'},
        ),
        migrations.AlterModelOptions(
            name='leagues',
            options={'verbose_name': 'league', 'verbose_name_plural': 'leagues'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'manager', 'verbose_name_plural': 'managers'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'match', 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.RemoveField(
            model_name='clubs',
            name='player',
        ),
        migrations.RemoveField(
            model_name='leagues',
            name='clubs',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='players',
        ),
        migrations.AddField(
            model_name='clubs',
            name='city',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='stadium_name',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leagues',
            name='country',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leagues',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Clubs'),
            preserve_default=False,
        ),
    ]
