# Generated by Django 2.1.1 on 2018-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clubs_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
    ]
