# Generated by Django 2.1.1 on 2018-09-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_matches_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.IntegerField(choices=[(0, 'Goalkeeper'), (1, 'Defender'), (2, 'Midfielder'), (3, 'Forward')]),
        ),
    ]
