# Generated by Django 2.1.1 on 2018-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180930_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='players',
            name='last_name',
        ),
        migrations.AddField(
            model_name='players',
            name='name',
            field=models.CharField(default='None', max_length=128),
            preserve_default=False,
        ),
    ]
