# Generated by Django 2.1.1 on 2018-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180930_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='date_of_birth',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='height',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='nationality',
            field=models.CharField(default='Poland', max_length=64),
            preserve_default=False,
        ),
    ]
