# Generated by Django 2.1.1 on 2018-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181001_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='away_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='home_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
