# Generated by Django 2.1.1 on 2018-10-04 13:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181004_1136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelTable(
            name='manager',
            table='manager',
        ),
    ]
