# Generated by Django 2.1.1 on 2018-10-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181004_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
