# Generated by Django 2.1.1 on 2018-10-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playershirtnumber',
            name='player',
        ),
        migrations.AddField(
            model_name='playershirtnumber',
            name='player',
            field=models.ManyToManyField(to='main.Players'),
        ),
    ]
