# Generated by Django 2.1.1 on 2018-10-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20181005_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playershirtnumber',
            name='player',
        ),
        migrations.AddField(
            model_name='playershirtnumber',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Players'),
            preserve_default=False,
        ),
    ]
