# Generated by Django 2.1.1 on 2018-10-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20181005_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playershirtnumber',
            name='player',
        ),
        migrations.AddField(
            model_name='players',
            name='shirt_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.PlayerShirtNumber'),
            preserve_default=False,
        ),
    ]
