# Generated by Django 2.1.1 on 2018-10-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20181005_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='shirt_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PlayerShirtNumber'),
        ),
    ]
