# Generated by Django 2.1.1 on 2018-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20181005_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='shirt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerShirtNumber',
        ),
    ]
